apiVersion: v1
kind: Service
metadata:
  labels:
    run: remoteweb
  name: remoteweb-service
  namespace: remote
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31999
  selector:
    run: remoteweb
  type: NodePort
status:
  loadBalancer: {}
